name = "Square"
license = "MIT"
licenselink = "https://github.com/kkatrio/square/blob/master/LICENSE"
description = ""
homepage = ""
tags = ["clean", "simple"]
features = []
min_version = "0.41"

[author]
  name = "Konstantinos Katrioplas"
  homepage = "http://dikatrio.com/"
